development:
  adapter: postgresql
  encoding: unicode
  database: art_shoppe_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: art_shoppe_test
  pool: 5
  username:
  password:


